config/routes.rb
Rails.application.routes.draw do
  # scope module: 'api', shallow: true  do
  #   scope module: 'v2' do
  #     resources :tests do
  #       resources :bests do
  #         resources :nests
  #       end
  #     end
  #   end
  # end

  scope module: 'api' do
    scope module: 'v1' do
      resources :users, shallow: true do
        resources :jobs do
          resources :parts do
            resources :tasks do
              resources :comments
            end
          end
        end
      end
    end
  end

  get 'new_session', to: 'api/v1/sessions#new', as: 'new_session'
  post 'create_session', to: 'api/v1/sessions#create', as: 'create_session'
  get 'logout_session', to: 'api/v1/sessions#logout', as: 'logout_session'
  get 'recover_password', to: 'api/v1/sessions#recover_password', as: 'recover_password'

  root 'api/v1/users#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/best.rb
class Best < ApplicationRecord
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :job
  belongs_to :part
  belongs_to :task
end

app/models/job.rb
class Job < ApplicationRecord
  has_many :parts
  has_many :tasks
  has_many :comments
  belongs_to :user
end

app/models/nest.rb
class Nest < ApplicationRecord
end

app/models/part.rb
class Part < ApplicationRecord
  has_many :tasks
  has_many :comments
  belongs_to :user
  belongs_to :job
end

app/models/score.rb
class Score < ApplicationRecord
end

app/models/task.rb
class Task < ApplicationRecord
  has_many :comments
  belongs_to :user
  belongs_to :job
  belongs_to :part
end

app/models/test.rb
class Test < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  has_many :jobs
  has_many :parts
  has_many :tasks
  has_many :comments

  has_secure_password

  validates :name, presence: true
  validates :email, uniqueness: true, presence: true
  validates :email, format: { with: /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i,
    message: "Wromg email format" }
  validates :password, presence: true, length: { minimum: 8, maximum: 64 }

  mount_uploader :avatar, AvatarUploader
end

app/helpers/bests_helper.rb
module BestsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/helpers/nests_helper.rb
module NestsHelper
end

app/helpers/parts_helper.rb
module PartsHelper
end

app/helpers/scores_helper.rb
module ScoresHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/tests_helper.rb
module TestsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MylistApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <%= render  template: 'layouts/navs/main' %>
      <%= render  template: 'layouts/navs/user_data' %>
      <%= render  template: 'layouts/navs/session' %>
    </header>
    <div class="previos_data">
      previos
    </div>
    <div class='layout_yeld'>
      <%= yield %>
    </div>
    <div class="next_data">
    next
    </div>
    <footer>
      <p><%= Api::V1::FooterController.date %></p>
    </footer>
  </body>
</html>

app/views/layouts/navs/main.html.erb
<div class="main">
  <%= link_to "GITHUB", 'https://github.com/keyhit/mylist-back' %>
</div>

app/views/layouts/navs/session.html.erb
<div class="session">
  <% unless current_user %>
    <%= link_to "Login", new_session_path %> | <%= link_to "Signup", new_user_path %>
  <% end %>
  <% if current_user %>
    <%= link_to "Logout", logout_session_path %>
  <% end %>
</div>

app/views/layouts/navs/side_main.html.erb
<!-- <div class="side_main">
  <h1>Side main to LIST page </h1>
</div> -->

app/views/layouts/navs/side_start.html.erb
<!-- <div class="side_start">
<h1>Welcome to LIST page </h1>
</div> -->

app/views/layouts/navs/user_data.html.erb
<div class="user_data">
  <% if current_user %>
    name: <%= current_user.name %> 
    email: <%= current_user.email %> 
  <% end %>
  </div>

app/views/layouts/navs/welcome.html.erb
<div class="welcome">
<h1>Welcome to LIST page </h1>
</div>